In [1]:
import numpy as np
import toolbox as *

In [2]:
lista=[1,2,3,4,5]
lista_array=np.array(lista)
print(lista_array)

[1 2 3 4 5]


In [4]:
print(np.mean(lista_array))

3.0


In [7]:
voti=np.array([[10,20,30],
               [34,54,65],
               [23,56,75]])
print(voti)

[[10 20 30]
 [34 54 65]
 [23 56 75]]


In [9]:
zero=np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
zero_2d=np.zeros((2,2))
print(zero_2d)
zero_2d_versione1=np.zeros(10,dtype=int)
print(zero_2d_versione1)

[[0. 0.]
 [0. 0.]]
[0 0 0 0 0 0 0 0 0 0]


In [13]:
uno=np.ones(20,dtype=int)
print(uno)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [19]:
a=np.arange(20)
print(a)
b=np.arange(1,20,2)
print(b)
c=np.arange(0,1,0.2)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[0.  0.2 0.4 0.6 0.8]


In [22]:
giorni=np.arange(1,32)          #giorni del mese
sabati=np.arange(6,32,7)
print(giorni,sabati)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31] [ 6 13 20 27]


In [31]:
numeri=np.linspace(1,20,9)
print(numeri)

[ 1.     3.375  5.75   8.125 10.5   12.875 15.25  17.625 20.   ]


In [32]:
numeri1=np.linspace(1,20,9,dtype=int)
print(numeri1)

[ 1  3  5  8 10 12 15 17 20]


In [44]:
tabella=np.array([[3,6,9],
                  [2,4,8],
                  [10,9,4]])


In [45]:
print("shape",tabella.shape)
print("ndim", tabella.ndim)
print("size", tabella.size)
print("dtype",tabella.dtype)

shape (3, 3)
ndim 2
size 9
dtype int64


In [65]:
nuovo=np.arange(12)
tabella3x4=nuovo.reshape(3,4)
print(nuovo)
print(tabella3x4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
d=nuovo.reshape(6,-1)
print(d)
e=nuovo.reshape(-1,4)
print(e)
f=nuovo.reshape(1,-1)
print(f)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [60]:
print(nuovo[-1])
print(tabella[0][0])

11
3


In [ ]:
dim3=np.array([[[2,3,4],[4,5,6],[65,3,2]],
               [[1,2,3],[345,21,3],[43,21,3]]])
print(dim3)

[[[  2   3   4]
  [  4   5   6]
  [ 65   3   2]]

 [[  1   2   3]
  [345  21   3]
  [ 43  21   3]]]


In [63]:
vista=nuovo[1:4]
vista[0]=9
print(vista)
print(nuovo)

[9 2 3]
[ 0  9  2  3  4  5  6  7  8  9 10 11]


In [68]:
print(nuovo)
copia=nuovo[1:4].copy()
copia[0]=8
print(copia)
print(nuovo)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[8 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [77]:
listanuova=[20,23,4,5,43,2135,5,67,7,67,76,56,5,3,56,67,7]
nuovo2=np.array(listanuova)
maschera=nuovo2>44
print(maschera)

[False False False False False  True False  True False  True  True  True
 False False  True  True False]


In [76]:
print(nuovo2[nuovo2>12])

[  20   23   43 2135   67   67   76   56   56   67]


In [80]:
dati=nuovo2[(nuovo2>= 20) | (nuovo2<=37)]
print(dati)

[  20   23    4    5   43 2135    5   67    7   67   76   56    5    3
   56   67    7]
