In [ ]:
import numpy as np
import toolbox as *

In [2]:
lista=[1,2,3,4,5]
lista_array=np.array(lista)
print(lista_array)

[1 2 3 4 5]


In [4]:
print(np.mean(lista_array))

3.0


In [7]:
voti=np.array([[10,20,30],
               [34,54,65],
               [23,56,75]])
print(voti)

[[10 20 30]
 [34 54 65]
 [23 56 75]]


In [9]:
zero=np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
zero_2d=np.zeros((2,2))
print(zero_2d)
zero_2d_versione1=np.zeros(10,dtype=int)
print(zero_2d_versione1)

[[0. 0.]
 [0. 0.]]
[0 0 0 0 0 0 0 0 0 0]


In [13]:
uno=np.ones(20,dtype=int)
print(uno)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [19]:
a=np.arange(20)
print(a)
b=np.arange(1,20,2)
print(b)
c=np.arange(0,1,0.2)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[0.  0.2 0.4 0.6 0.8]


In [22]:
giorni=np.arange(1,32)          #giorni del mese
sabati=np.arange(6,32,7)
print(giorni,sabati)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31] [ 6 13 20 27]
