In [1]:
import numpy as np

In [4]:
arr2=np.array([[1,2],
               [3,4]])

In [2]:
array3per2=np.array([[1,2,3],
                     [4,5,6]])
operazione1=array3per2.T
operazione2=np.transpose(array3per2)
operazione3=array3per2.transpose()
print(operazione1,operazione2,operazione3, sep="\n")


[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [5]:
matrice=np.linalg.det(arr2)
print(matrice)

-2.0000000000000004


In [12]:
#A*x=B
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
B=np.array([12,34,6])
detA = np.linalg.det(A)
print("det(A):", detA)
x = np.linalg.solve(A, B)
print("Soluzione (np.linalg.solve):", x)
print("Residuo (A@x - b):", A @ x - B)

det(A): 0.0


LinAlgError: Singular matrix

In [13]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([12, 34, 6])


print("A:\n", A)
print("b:", B)


# Controllo del determinante per verificare singolarità
detA = np.linalg.det(A)
print("det(A):", detA)


if abs(detA) < 1e-12:
    print("Matrice singolare o mal condizionata — uso una soluzione ai minimi quadrati (np.linalg.lstsq) e la pseudo-inversa per confronto.")
    x_lstsq, residuals, rank, s = np.linalg.lstsq(A, B, rcond=None)
    x_pinv = np.linalg.pinv(A) @ B
    print("Soluzione (lstsq):", x_lstsq)
    print("Soluzione (pinv):", x_pinv)
    if residuals.size:
        print("Residui (lstsq):", residuals)
    else:
        print("Residui (lstsq): Nessuno (sistema compatibile o sotto-determinato)")
    print("Confronto allclose (lstsq vs pinv):", np.allclose(x_lstsq, x_pinv))
else:
    x = np.linalg.solve(A, B)
    print("Soluzione (np.linalg.solve):", x)
    print("Residuo (A@x - b):", A @ x - B)

A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b: [12 34  6]
det(A): 0.0
Matrice singolare o mal condizionata — uso una soluzione ai minimi quadrati (np.linalg.lstsq) e la pseudo-inversa per confronto.
Soluzione (lstsq): [-11.5         -0.33333333  10.83333333]
Soluzione (pinv): [-11.5         -0.33333333  10.83333333]
Residui (lstsq): Nessuno (sistema compatibile o sotto-determinato)
Confronto allclose (lstsq vs pinv): True


In [26]:
#U10->Unicode, max 10 caratteri / i4->Int 32bit, max 4 cifre / f4->float 64bit, max 4 cifre
dtype_person = [('nome', 'U10'), ('eta', 'i4'), ('altezza', 'f4')]
people = np.array([
    ('Anna', 28, 1.68),
    ('Luca', 35, 1.75),
    ('Marco', 22, 1.80),
    ('Luca', 37, 1.95)
], dtype=dtype_person)
print(people)
print("Nomi:", people['nome'])
print("Età media:", people['eta'].mean())
young = people[people['eta'] < 30]
print("Giovani (<30):")
print(young)
print("Primo record:", people[0])
print("Altezza di Luca:", people[people['nome'] == 'Luca']['altezza'][0])
print("Altezze in cm:", people['altezza'] * 100)
rec = people.view(np.recarray)
print("Accesso come attributo (rec.nome):", rec.nome)

[('Anna', 28, 1.68) ('Luca', 35, 1.75) ('Marco', 22, 1.8 )
 ('Luca', 37, 1.95)]
Nomi: ['Anna' 'Luca' 'Marco' 'Luca']
Età media: 30.5
Giovani (<30):
[('Anna', 28, 1.68) ('Marco', 22, 1.8 )]
Primo record: ('Anna', 28, 1.68)
Altezza di Luca: 1.75
Altezze in cm: [168. 175. 180. 195.]
Accesso come attributo (rec.nome): ['Anna' 'Luca' 'Marco' 'Luca']


In [ ]:
elem=np.array([-2,3,4,-8,5])
var=np.where(elem<0,0,elem)
print(var)
ind=np.where(elem>2)
print(ind)
comp=np.where((elem>0) & (elem<5),elem*2,elem)
print(comp)

[0 3 4 0 5]
(array([1, 2, 4]),)
[-2  6  8 -8  5]


In [39]:
# np.select per più condizioni
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Array originale:", arr)
condizioni = [arr < 3, (arr >= 3) & (arr <= 6), arr > 6]
scelte = ['basso', 'medio', 'alto']
labels = np.select(condizioni, scelte, default='sconosciuto')


print("Array:", arr)
print("Condizioni:", [c.tolist() for c in condizioni])
print("Etichette (np.select):", labels)


# Esempio pratico: creare una nuova colonna numerica in base alle condizioni
valori = np.select(condizioni, [0, 1, 2], default=-1)
print("Valori numerici associati:", valori)

Array originale: [1 2 3 4 5 6 7 8 9]
Array: [1 2 3 4 5 6 7 8 9]
Condizioni: [[True, True, False, False, False, False, False, False, False], [False, False, True, True, True, True, False, False, False], [False, False, False, False, False, False, True, True, True]]
Etichette (np.select): ['basso' 'basso' 'medio' 'medio' 'medio' 'medio' 'alto' 'alto' 'alto']
Valori numerici associati: [0 0 1 1 1 1 2 2 2]
