In [1]:
import numpy as np
import os

In [2]:
arr = np.array([3, 1, 4, 1, 5])
# Crea una copia ordinata
ordinato = np.sort(arr)


print("Originale:", arr)
print("Ordinato:", ordinato)

Originale: [3 1 4 1 5]
Ordinato: [1 1 3 4 5]


In [3]:
arr.sort()
print(arr)

[1 1 3 4 5]


In [5]:
nomi = np.array(['Mario', 'Laura', 'Giuseppe'])
voti = np.array([7.5, 9.0, 8.0])
indice=np.argsort(voti)
print(indice)
for numero in indice:
    print(f"{nomi[numero]} : {voti[numero]}")

[0 2 1]
Mario : 7.5
Giuseppe : 8.0
Laura : 9.0


In [9]:
studenti = np.array([
    ('Mario', 25, 8.5),
    ('Laura', 23, 9.0),
    ('Giuseppe', 27, 7.5)
], dtype=[('nome', 'U10'), ('età', 'i4'), ('voto', 'f4')])
ordvoto=np.sort(studenti, order="voto")
print(ordvoto)
ordvoto1=np.sort(studenti, order=["età","voto"])
print(ordvoto1)
ordecrescente=np.sort(studenti, order="voto")[::-1]
print(ordecrescente)

[('Giuseppe', 27, 7.5) ('Mario', 25, 8.5) ('Laura', 23, 9. )]
[('Laura', 23, 9. ) ('Mario', 25, 8.5) ('Giuseppe', 27, 7.5)]
[('Laura', 23, 9. ) ('Mario', 25, 8.5) ('Giuseppe', 27, 7.5)]


In [11]:
matrice = np.array([[3, 1, 4],
                    [1, 5, 9],
                    [2, 6, 5]])
matord=np.sort(matrice, axis=0)
matord1=np.sort(matrice, axis=1)
print(matord)
print(matord1)

[[1 1 4]
 [2 5 5]
 [3 6 9]]
[[1 3 4]
 [1 5 9]
 [2 5 6]]


In [17]:
# Array ordinato
arr = np.array([1, 3, 5, 7, 9])


# Dove dovrei inserire 6?
idx = np.searchsorted(arr, 6)
print(f"Inserisci 6 alla posizione: {idx}")


# Verifica
arr_nuovo = np.insert(arr, idx, 6)
print(f"Nuovo array: {arr_nuovo}")
print()


# Inserire più valori
valori = [2, 6, 8]
for val in valori:
    idx = np.searchsorted(arr, val)
    print(f"Valore {val} dovrebbe andare alla posizione {idx}")

Inserisci 6 alla posizione: 3
Nuovo array: [1 3 5 6 7 9]

Valore 2 dovrebbe andare alla posizione 1
Valore 6 dovrebbe andare alla posizione 3
Valore 8 dovrebbe andare alla posizione 4


In [20]:
arr = np.array([1, 3, 5, 7, 9])
min=np.argmin(arr)
max=np.argmax(arr)
print(min)
print(max)

0
4


In [23]:
matrice = np.array([[1, 0, 2],
                    [6, 3, 0],
                    [4, 0, 5]])
print(np.argmin(matrice, axis=0))
print(np.argmin(matrice, axis=1))

[0 0 1]
[1 2 1]


In [24]:
arr5 = np.array([0, 1, 0, 3, 0, 5])
indici=np.nonzero(arr5)
print(indici)

(array([1, 3, 5]),)


In [26]:
# Accedi ai valori non-zero
valori_nonzero = arr5[np.nonzero(arr5)]
print(f"Valori non-zero: {valori_nonzero}")  # [1 3 5]
print()


# Con matrici
matrice = np.array([[1, 0, 2],
                    [0, 3, 0],
                    [4, 0, 5]])


print("Posizioni degli elementi non-zero (matrice):")
indici_mat = np.nonzero(matrice)
for riga, col in zip(indici_mat[0], indici_mat[1]):
    print(f"({riga}, {col}): {matrice[riga, col]}")

Valori non-zero: [1 3 5]

Posizioni degli elementi non-zero (matrice):
(0, 0): 1
(0, 2): 2
(1, 1): 3
(2, 0): 4
(2, 2): 5


In [27]:
array2d=np.array([[10,20,30],
                  [40,50,60]])
np.save("array2d.npy", array2d)

In [29]:
dati_caricati=np.load("array2d.npy")
print(dati_caricati)
print(f"Tipo: {dati_caricati.dtype}")
print(f"Forma: {dati_caricati.shape}")

[[10 20 30]
 [40 50 60]]
Tipo: int64
Forma: (2, 3)


In [44]:
dati = np.array([[1.234, 5.678, 9.012],
                 [2.345, 6.789, 0.123]])
# CSV semplice
np.savetxt('dati.csv', dati,
           delimiter=' , ',
           fmt='%.3f',
           header='Col1, Col2, Col3',
           comments='tabella\n')


print("CSV salvato!")

CSV salvato!


In [47]:
# Caricamento con np.loadtxt()
dati_csv = np.loadtxt('dati.csv', delimiter=',', skiprows=2)
print(f"Dati caricati:\n{dati_csv}")
print()
x, y = np.loadtxt('dati.csv', delimiter=',', usecols=(0, 1), unpack=True, skiprows=2)
print(f"Colonna X: {x}")
print(f"Colonna Y: {y}")

Dati caricati:
[[1.234 5.678 9.012]
 [2.345 6.789 0.123]]

Colonna X: [1.234 2.345]
Colonna Y: [5.678 6.789]
